from django.core.management.base import BaseCommand
from WW.models import Currency

class Command(BaseCommand):
    help = 'Populates the database with currency data'

    def handle(self, *args, **options):
        currencies = [
            ('USD', 'United States Dollar', '$'),
            ('EUR', 'Euro', '€'),
            ('GBP', 'British Pound', '£'),
            ('INR', 'Indian Rupee', '₹'),
            ('AUD', 'Australian Dollar', 'A$'),
            ('CAD', 'Canadian Dollar', 'C$'),
            ('SGD', 'Singapore Dollar', 'S$'),
            ('MYR', 'Malaysian Ringgit', 'RM'),
            ('JPY', 'Japanese Yen', '¥'),
            ('CNY', 'Chinese Yuan', '¥'),
            ('HKD', 'Hong Kong Dollar', 'HK$'),
            ('NZD', 'New Zealand Dollar', 'NZ$'),
            ('SEK', 'Swedish Krona', 'kr'),
            ('NOK', 'Norwegian Krone', 'kr'),
            ('CHF', 'Swiss Franc', 'CHF'),
            ('DKK', 'Danish Krone', 'kr'),
            ('RUB', 'Russian Ruble', '₽'),
            ('ZAR', 'South African Rand', 'R'),
            ('BRL', 'Brazilian Real', 'R$'),
            ('TRY', 'Turkish Lira', '₺'),
            ('KRW', 'South Korean Won', '₩'),
            ('AED', 'UAE Dirham', 'د.إ'),
            ('SAR', 'Saudi Riyal', 'ر.س'),
            ('QAR', 'Qatari Riyal', 'ر.ق'),
            ('KWD', 'Kuwaiti Dinar', 'د.ك'),
            ('OMR', 'Omani Rial', 'ر.ع.'),
            ('BHD', 'Bahraini Dinar', 'ب.د'),
            ('JOD', 'Jordanian Dinar', 'د.ا'),
            ('EGP', 'Egyptian Pound', 'ج.م'),
            ('THB', 'Thai Baht', '฿'),
            ('IDR', 'Indonesian Rupiah', 'Rp'),
            ('PHP', 'Philippine Peso', '₱'),
            ('PKR', 'Pakistani Rupee', '₨'),
            ('LKR', 'Sri Lankan Rupee', 'Rs'),
            ('BDT', 'Bangladeshi Taka', '৳'),
            ('NPR', 'Nepalese Rupee', 'रू'),
            ('MMK', 'Myanmar Kyat', 'K'),
            ('VND', 'Vietnamese Dong', '₫'),
            ('KHR', 'Cambodian Riel', '៛'),
            ('KZT', 'Kazakhstani Tenge', '₸'),
            ('UZS', 'Uzbekistani Som', 'лв'),
            ('TJS', 'Tajikistani Somoni', 'ЅМ'),
            ('GHS', 'Ghanaian Cedi', 'GH₵'),
            ('KES', 'Kenyan Shilling', 'KSh'),
            ('NGN', 'Nigerian Naira', '₦'),
            ('UGX', 'Ugandan Shilling', 'USh'),
            ('TZS', 'Tanzanian Shilling', 'TSh'),
            ('ARS', 'Argentine Peso', '$'),
            ('CLP', 'Chilean Peso', '$'),
            ('COP', 'Colombian Peso', '$'),
            ('PEN', 'Peruvian Sol', 'S/.'),
            ('UYU', 'Uruguayan Peso', '$U'),
            ('BOB', 'Bolivian Boliviano', 'Bs.'),
            ('PYG', 'Paraguayan Guarani', '₲'),
            ('VEF', 'Venezuelan Bolívar', 'Bs.F'),
            ('MXN', 'Mexican Peso', '$'),
            ('CRC', 'Costa Rican Colón', '₡'),
            ('GTQ', 'Guatemalan Quetzal', 'Q'),
            ('HNL', 'Honduran Lempira', 'L'),
            ('NIO', 'Nicaraguan Córdoba', 'C$'),
            ('PAB', 'Panamanian Balboa', 'B/.'),
            ('DOP', 'Dominican Peso', 'RD$'),
            ('CUP', 'Cuban Peso', '$MN'),
            ('JMD', 'Jamaican Dollar', 'J$'),
            ('HTG', 'Haitian Gourde', 'G'),
            ('BSD', 'Bahamian Dollar', '$'),
            ('BBD', 'Barbadian Dollar', 'Bds$'),
            ('BZD', 'Belize Dollar', 'BZ$'),
            ('KYD', 'Cayman Islands Dollar', '$'),
            ('XCD', 'East Caribbean Dollar', '$'),
            ('TTD', 'Trinidad and Tobago Dollar', 'TT$'),
            ('BMD', 'Bermudian Dollar', '$'),
            ('ANG', 'Netherlands Antillean Guilder', 'ƒ'),
            ('AWG', 'Aruban Florin', 'ƒ'),
            ('SRD', 'Surinamese Dollar', '$'),
            ('GYD', 'Guyanese Dollar', 'G$'),
            ('BIF', 'Burundian Franc', 'FBu'),
            ('CVE', 'Cape Verdean Escudo', '$'),
            ('DJF', 'Djiboutian Franc', 'Fdj'),
            ('ERN', 'Eritrean Nakfa', 'Nfk'),
            ('ETB', 'Ethiopian Birr', 'Br'),
            ('GMD', 'Gambian Dalasi', 'D'),
            ('GNF', 'Guinean Franc', 'FG'),
            ('LSL', 'Lesotho Loti', 'L'),
            ('LRD', 'Liberian Dollar', '$'),
            ('MWK', 'Malawian Kwacha', 'MK'),
            ('MRO', 'Mauritanian Ouguiya', 'UM'),
            ('MUR', 'Mauritian Rupee', '₨'),
            ('MZN', 'Mozambican Metical', 'MT'),
            ('NAD', 'Namibian Dollar', '$'),
            ('RWF', 'Rwandan Franc', 'FRw'),
            ('SCR', 'Seychellois Rupee', '₨'),
            ('SLL', 'Sierra Leonean Leone', 'Le'),
            ('SOS', 'Somali Shilling', 'Sh.so.'),
            ('SZL', 'Swazi Lilangeni', 'E'),
            ('ZMW', 'Zambian Kwacha', 'ZK'),
            ('BWP', 'Botswana Pula', 'P'),
            ('AOA', 'Angolan Kwanza', 'Kz'),
            ('MGA', 'Malagasy Ariary', 'Ar'),
            ('CDF', 'Congolese Franc', 'FC'),
            ('SDG', 'Sudanese Pound', 'ج.س.'),
            ('SSP', 'South Sudanese Pound', '£'),
            ('SHP', 'Saint Helena Pound', '£'),
            ('STD', 'São Tomé and Príncipe Dobra', 'Db'),
            ('TND', 'Tunisian Dinar', 'د.ت'),
            ('MAD', 'Moroccan Dirham', 'د.م.'),
            ('DZD', 'Algerian Dinar', 'د.ج'),
            ('LYD', 'Libyan Dinar', 'ل.د'),
            ('MRU', 'Mauritanian Ouguiya', 'UM'),
            ('SYP', 'Syrian Pound', '£S'),
            ('YER', 'Yemeni Rial', '﷼'),
            ('AFN', 'Afghan Afghani', '؋'),
            ('AMD', 'Armenian Dram', '֏'),
            ('AZN', 'Azerbaijani Manat', '₼'),
            ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM'),
            ('GEL', 'Georgian Lari', '₾'),
            ('IRR', 'Iranian Rial', '﷼'),
            ('IQD', 'Iraqi Dinar', 'ع.د'),
            ('ILS', 'Israeli New Shekel', '₪'),
            ('KGS', 'Kyrgyzstani Som', 'лв'),
            ('LBP', 'Lebanese Pound', 'ل.ل'),
            ('MDL', 'Moldovan Leu', 'L'),
            ('TMT', 'Turkmenistani Manat', 'm'),
            ('UZS', 'Uzbekistani Som', 'лв'),
            ('YER', 'Yemeni Rial', '﷼'),
            ('BYN', 'Belarusian Ruble', 'Br'),
            ('BGN', 'Bulgarian Lev', 'лв'),
            ('HRK', 'Croatian Kuna', 'kn'),
            ('CZK', 'Czech Koruna', 'Kč'),
            ('HUF', 'Hungarian Forint', 'Ft'),
            ('PLN', 'Polish Zloty', 'zł'),
            ('RON', 'Romanian Leu', 'lei'),
            ('RSD', 'Serbian Dinar', 'дин.'),
            ('UAH', 'Ukrainian Hryvnia', '₴'),
            ('ISK', 'Icelandic Króna', 'kr'),
            ('ALL', 'Albanian Lek', 'L'),
            ('MKD', 'Macedonian Denar', 'ден'),
            ('MNT', 'Mongolian Tögrög', '₮'),
            ('KPW', 'North Korean Won', '₩'),
            ('LAK', 'Lao Kip', '₭'),
            ('MMK', 'Myanmar Kyat', 'K'),
            ('BND', 'Brunei Dollar', '$'),
            ('KHR', 'Cambodian Riel', '៛'),
            ('KZT', 'Kazakhstani Tenge', '₸'),
            ('LAK', 'Lao Kip', '₭'),
            ('MNT', 'Mongolian Tögrög', '₮'),
            ('MMK', 'Myanmar Kyat', 'K'),
            ('KPW', 'North Korean Won', '₩'),
            ('TWD', 'New Taiwan Dollar', 'NT$'),
            ('PGK', 'Papua New Guinean Kina', 'K'),
            ('WST', 'Samoan Tala', 'T'),
            ('SBD', 'Solomon Islands Dollar', '$'),
            ('TOP', 'Tongan Paʻanga', 'T$'),
            ('VUV', 'Vanuatu Vatu', 'Vt'),
            ('FJD', 'Fijian Dollar', '$'),
            ('KID', 'Kiribati Dollar', '$'),
            ('SHP', 'Saint Helena Pound', '£'),
            ('FKP', 'Falkland Islands Pound', '£'),
            ('GIP', 'Gibraltar Pound', '£'),
            ('GGP', 'Guernsey Pound', '£'),
            ('IMP', 'Isle of Man Pound', '£'),
            ('JEP', 'Jersey Pound', '£'),
            ('SPL', 'Seborga Luigino', '£'),
            ('TVD', 'Tuvaluan Dollar', '$'),
            ('ZWL', 'Zimbabwean Dollar', '$'),
        ]

        for code, name, symbol in currencies:
            Currency.objects.get_or_create(code=code, defaults={'name': name, 'symbol': symbol})

        self.stdout.write(self.style.SUCCESS('Successfully added currencies.'))