# Generated by Django 5.1.4 on 2025-02-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0019_remove_expense_date_remove_income_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW.user')),
            ],
            options={
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
