# Generated by Django 5.1.4 on 2025-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0020_monthlyfinance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='january', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='january', max_length=100),
        ),
        migrations.DeleteModel(
            name='MonthlyFinance',
        ),
    ]
