# Generated by Django 5.1.4 on 2025-02-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0021_expense_month_income_month_delete_monthlyfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='WW.currency'),
            preserve_default=False,
        ),
    ]
