# Generated by Django 5.1.4 on 2025-02-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0022_currency_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
    ]
