# Generated by Django 5.1.4 on 2025-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0023_alter_currency_code_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
