# Generated by Django 5.1.4 on 2025-02-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0025_alter_user_currency'),
    ]

    operations = [
    ]
