# Generated by Django 5.1.4 on 2025-02-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0026_auto_20250224_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='WW.currency'),
            preserve_default=False,
        ),
    ]
