# Generated by Django 5.1.4 on 2025-02-25 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0030_expense_currency_income_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='income',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WW.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW.user')),
            ],
        ),
    ]
