# Generated by Django 5.1.4 on 2025-03-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0033_bill_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WW.expense'),
        ),
        migrations.AddField(
            model_name='goal',
            name='incomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WW.income'),
        ),
    ]
