name: Daily Bill Reminder

on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Start MySQL Service
        run: sudo systemctl start mysql

      - name: Debug MySQL Connection
        run: |
          mysql -uroot -pdev@2006 -e "SHOW DATABASES;"

      - name: Set Up Database
        run: |
          mysql -uroot -pdev@2006 -e "CREATE DATABASE IF NOT EXISTS wealthwise;"
          mysql -uroot -pdev@2006 -e "CREATE USER IF NOT EXISTS 'django_user'@'localhost' IDENTIFIED BY 'django_password';"
          mysql -uroot -pdev@2006 -e "GRANT ALL PRIVILEGES ON wealthwise.* TO 'django_user'@'localhost';"
          mysql -uroot -pdev@2006 -e "FLUSH PRIVILEGES;"

      - name: Set Up Django Environment
        env:
          DJANGO_SETTINGS_MODULE: p.settings
        run: |
          cd p
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Reminder Script
        env:
          EMAIL_HOST_USER: wealthwise200@gmail.com
          EMAIL_HOST_PASSWORD: hcayuxvpkvetdcxx'
        run: |
          cd p
          python reminder.py
