name: Daily Bill Reminder

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install django mysqlclient 

      - name: Setup Database (MySQL)
        run: |
          sudo systemctl start mysql
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS wealthwise;"
          mysql -u root -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'dev@2006';"
          mysql -u root -e "GRANT ALL PRIVILEGES ON wealthwise.* TO 'root'@'localhost';"
          mysql -u root -e "FLUSH PRIVILEGES;"

      - name: Set Up Django Environment
        run: |
          export DJANGO_SETTINGS_MODULE=p.settings
          export DATABASE_NAME=wealthwise
          export DATABASE_USER=root
          export DATABASE_PASSWORD=dev@2006
          export DATABASE_HOST=localhost
          export DATABASE_PORT=3306
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Reminder Script
        env:
          EMAIL_HOST_USER: wealthwise200@gmail.com
          EMAIL_HOST_PASSWORD: hcayuxvpkvetdcxx
        run: python reminder.py
