name: Daily Bill Reminder

on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Check directory structure
        run: |
          pwd
          ls -la
          find . -name "manage.py"
          find . -name "requirements.txt"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install django mysqlclient django-tailwind plotly
          fi

      - name: Debug installed packages
        run: pip list

      - name: Setup MySQL Database
        env:
          DB_NAME: wealthwise
          DB_USER: root
          DB_PASSWORD: dev@2006
          MYSQL_ROOT_PASSWORD: "root"  # Default root password for MySQL in GitHub Actions
        run: |
          sudo systemctl start mysql
          sudo mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
          sudo mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
          sudo mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
          sudo mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"

      - name: Set Up Django Environment
        env:
          DJANGO_SETTINGS_MODULE: wealthwise.settings  # Update with your actual Django project name
          DATABASE_NAME: wealthwise
          DATABASE_USER: root
          DATABASE_PASSWORD: dev@2006
          DATABASE_HOST: localhost
          DATABASE_PORT: 3306
        run: |
          PROJECT_DIR=$(find . -name "manage.py" -exec dirname {} \;)
          cd $PROJECT_DIR
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Reminder Script
        env:
          EMAIL_HOST_USER: wealthwise200@gmail.com
          EMAIL_HOST_PASSWORD: hcayuxvpkvetdcxx  # Remove extra `'` in your original script
        run: |
          PROJECT_DIR=$(find . -name "manage.py" -exec dirname {} \;)
          cd $PROJECT_DIR
          python reminder.py
  